### ISSUE TITLE
NativeScript 7 update

### ISSUE THREAD

**Issue by kaanguru** [EddyVerbruggen/nativescript-clipboard#16]
Is NativeScript 7 update coming anytime soon?

https://nativescript.org/blog/nativescript-7-for-plugin-authors/

**Comment by EddyVerbruggen** [comment]
NativeScript 7 update #16

**Comment by EddyVerbruggen** [comment]
I just released version 2.0.0 which should be NativeScript 7 compatible (the embedded demo app at least is).
